version: '3.4'

services:
  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: jandrey15/johnserrano-web
    # env_file:
    #   - web-variables.env
    container_name: web
    restart: always
    networks:
      app-network:
        aliases:
          - johnserrano.test
          - johnserrano.xyz
    # expose:
    #   - "3000"
    environment:
      API_URL: "${API_URL}"
      API_KEY: "${API_KEY}"
      STATIC_URL: "${STATIC_URL}"

  ghost:
    # image: ghost:1-alpine
    image: ghost:2.22-alpine
    container_name: ghost
    restart: always
    depends_on:
      - db
    expose:
      - "2368"
      - "443"
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: "${USER}"
      database__connection__password: "${PASSWORD}"
      database__connection__database: "${DATABASE}"
      NODE_ENV: "${NODE_ENV}"
      url: "${URL}"
      admin_url: "${URL}"
      # admin__url: http://admin.johnserrano.test:8080
    volumes:
      - ./ghost/blog:/var/lib/ghost/content
    networks:
      app-network:
        aliases:
          - admin.johnserrano.test
          - api.johnserrano.test
          - static.johnserrano.test
          # Prod port 80
          - admin.johnserrano.xyz
          - api.johnserrano.xyz
          - static.johnserrano.xyz
          # # Prod port 443
          - admin.johnserrano.xyz:443
          - api.johnserrano.xyz:443
          - static.johnserrano.xyz:443

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - dbghost:/var/lib/mysql 
    networks:
      - app-network
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: jandrey15/johnserrano-nginx
    container_name: nginx
    restart: always
    depends_on:
      - ghost
      - web
    networks:
      - app-network
    ports:
      - "80:80"
      - "2368:2368"
      # - "443:443"

networks:
  app-network:
    driver: bridge

volumes:
  dbghost:
  node_modules: 