version: '3.3'

services:
  web:
    # image: jandrey15/johnserrano-web
    build: ../frontend
    # env_file:
    #   - web-variables.env
    restart: always
    networks:
      - app-network
    ports:
      - "3000:3000"

  ghost:
    # image: ghost:1-alpine
    image: ghost:2.22-alpine
    restart: always
    depends_on:
      - db
    ports:
      - 8080:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: "${USER}"
      database__connection__password: "${PASSWORD}"
      database__connection__database: "${DATABASE}"
      url: http://johnserrano.test:8080
      admin__url: http://admin.johnserrano.test:8080
    volumes:
      - ./ghost/blog:/var/lib/ghost/content
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - dbghost:/var/lib/mysql 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbghost:
  node_modules: 